import type { Workflow } from './types';

/**
 * Export a workflow as JSON
 * @param workflow The workflow to export
 * @returns JSON string representation of the workflow
 */
export function exportWorkflow(workflow: Workflow): string {
  // Create a simplified representation of the workflow for export
  // Exclude fields that are specific to the current system instance
  const exportData = {
    name: workflow.name,
    description: workflow.description,
    definition: workflow.definition,
    createdAt: workflow.createdAt,
    updatedAt: workflow.updatedAt,
    // Don't export system-specific fields like id, status, currentVersion, isTemplate
  };

  return JSON.stringify(exportData, null, 2);
}

/**
 * Import a workflow from JSON
 * @param jsonStr The JSON string representation of the workflow
 * @param newName Optional new name for the imported workflow
 * @param newDescription Optional new description for the imported workflow
 * @returns Workflow object ready for import
 */
export function importWorkflow(jsonStr: string, newName?: string, newDescription?: string): Workflow {
  const importData = JSON.parse(jsonStr);
  
  // Generate a new ID (this will be handled by the backend)
  return {
    id: '', // Will be generated by the backend
    name: newName || importData.name,
    description: newDescription || importData.description || '',
    status: 'draft', // New imports start as draft
    currentVersion: 1,
    definition: importData.definition,
    isTemplate: false, // Imported workflows are not templates
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  };
}

/**
 * Download workflow as JSON file
 * @param workflow The workflow to export
 */
export function downloadWorkflow(workflow: Workflow): void {
  const dataStr = exportWorkflow(workflow);
  const dataUri = 'data:application/json;charset=utf-8,'+ encodeURIComponent(dataStr);
  
  const exportFileDefaultName = `${workflow.name.replace(/\s+/g, '_')}_workflow.json`;
  
  const linkElement = document.createElement('a');
  linkElement.setAttribute('href', dataUri);
  linkElement.setAttribute('download', exportFileDefaultName);
  linkElement.click();
}

/**
 * Read JSON file from input element
 * @param file The JSON file to read
 * @returns Promise that resolves to the content of the file
 */
export function readWorkflowFile(file: File): Promise<string> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = (event) => {
      try {
        const content = event.target?.result as string;
        // Validate that it's a proper workflow JSON
        JSON.parse(content);
        resolve(content);
      } catch (error) {
        reject(new Error('Invalid workflow JSON file'));
      }
    };
    reader.onerror = () => reject(new Error('Error reading file'));
    reader.readAsText(file);
  });
}

/**
 * Import workflow from JSON string and create it via API
 * @param jsonStr JSON string representing the workflow
 * @param apiCreateWorkflow Function to call to create the workflow via API
 * @returns Created workflow
 */
export async function importWorkflowViaApi(
  jsonStr: string,
  apiCreateWorkflow: (name: string, description: string, definition: any) => Promise<Workflow>
): Promise<Workflow> {
  const importData = JSON.parse(jsonStr);
  
  if (!importData.name || !importData.definition) {
    throw new Error('Invalid workflow format: missing name or definition');
  }
  
  // Create the workflow via the API
  return apiCreateWorkflow(
    importData.name,
    importData.description || '',
    importData.definition
  );
}